const colors = {
  light: {
    text: '#0F172A',
    tint: '#1B4FD8',
    background: '#F8FAFC',
    foreground: '#0F172A',
    card: '#FFFFFF',
    cardForeground: '#0F172A',
    primary: '#1B4FD8',
    primaryForeground: '#FFFFFF',
    secondary: '#EEF2FF',
    secondaryForeground: '#1B4FD8',
    muted: '#F1F5F9',
    mutedForeground: '#64748B',
    accent: '#F59E0B',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#E2E8F0',
    input: '#E2E8F0',
  },
  dark: {
    text: '#F8FAFC',
    tint: '#3B71E8',
    background: '#0F172A',
    foreground: '#F8FAFC',
    card: '#1E293B',
    cardForeground: '#F8FAFC',
    primary: '#3B71E8',
    primaryForeground: '#FFFFFF',
    secondary: '#1E3A5F',
    secondaryForeground: '#93C5FD',
    muted: '#1E293B',
    mutedForeground: '#94A3B8',
    accent: '#F59E0B',
    accentForeground: '#0F172A',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#334155',
    input: '#334155',
  },
  radius: 12,
};

export default colors;
