export interface Listing {
  id: string;
  name: string;
  category: string;
  rating: number;
  reviewCount: number;
  address: string;
  city: string;
  phone: string;
  website: string;
  hours: string;
  description: string;
  tags: string[];
  featured: boolean;
  verified: boolean;
  priceRange: string;
  color: string;
  initials: string;
}

export interface Category {
  id: string;
  label: string;
  icon: string;
  sfSymbol: string;
}

export const CATEGORIES: Category[] = [
  { id: 'all', label: 'All', icon: 'grid', sfSymbol: 'square.grid.2x2' },
  { id: 'restaurants', label: 'Restaurants', icon: 'coffee', sfSymbol: 'fork.knife' },
  { id: 'healthcare', label: 'Healthcare', icon: 'heart', sfSymbol: 'cross.case' },
  { id: 'services', label: 'Services', icon: 'tool', sfSymbol: 'wrench.and.screwdriver' },
  { id: 'shopping', label: 'Shopping', icon: 'shopping-bag', sfSymbol: 'bag' },
  { id: 'entertainment', label: 'Entertainment', icon: 'film', sfSymbol: 'ticket' },
  { id: 'education', label: 'Education', icon: 'book', sfSymbol: 'book.closed' },
  { id: 'real-estate', label: 'Real Estate', icon: 'home', sfSymbol: 'building.2' },
];

export const SAMPLE_LISTINGS: Listing[] = [
  {
    id: '1',
    name: 'The Golden Fork',
    category: 'restaurants',
    rating: 4.8,
    reviewCount: 342,
    address: '123 Main Street',
    city: 'New York, NY',
    phone: '+1 (212) 555-0101',
    website: 'https://example.com',
    hours: 'Mon–Fri 11am–10pm · Sat–Sun 10am–11pm',
    description: 'An award-winning farm-to-table restaurant offering seasonal menus crafted from locally sourced ingredients. Our chefs work directly with regional farms to bring you the freshest flavors each season.',
    tags: ['Farm-to-Table', 'Fine Dining', 'Wine Bar'],
    featured: true,
    verified: true,
    priceRange: '$$$',
    color: '#D4A847',
    initials: 'GF',
  },
  {
    id: '2',
    name: 'Sakura Sushi House',
    category: 'restaurants',
    rating: 4.6,
    reviewCount: 218,
    address: '45 Ocean Drive',
    city: 'Miami, FL',
    phone: '+1 (305) 555-0202',
    website: 'https://example.com',
    hours: 'Tue–Sun 12pm–10pm',
    description: 'Authentic Japanese cuisine with fresh sushi, sashimi, and immersive omakase dining experiences. Our head chef trained in Osaka for over a decade.',
    tags: ['Japanese', 'Sushi', 'Omakase'],
    featured: false,
    verified: true,
    priceRange: '$$',
    color: '#C57BA4',
    initials: 'SS',
  },
  {
    id: '3',
    name: 'Bright Smiles Dental',
    category: 'healthcare',
    rating: 4.9,
    reviewCount: 512,
    address: '78 Health Avenue',
    city: 'Austin, TX',
    phone: '+1 (512) 555-0303',
    website: 'https://example.com',
    hours: 'Mon–Fri 8am–6pm · Sat 9am–2pm',
    description: 'Modern dental care with a gentle touch. Offering everything from routine cleanings to advanced cosmetic dentistry in a comfortable, anxiety-free environment.',
    tags: ['Dentistry', 'Cosmetic', 'Family Care'],
    featured: true,
    verified: true,
    priceRange: '$$',
    color: '#4A90C4',
    initials: 'BS',
  },
  {
    id: '4',
    name: 'Wellness First Clinic',
    category: 'healthcare',
    rating: 4.7,
    reviewCount: 189,
    address: '200 Care Boulevard',
    city: 'Seattle, WA',
    phone: '+1 (206) 555-0404',
    website: 'https://example.com',
    hours: 'Mon–Fri 7am–7pm',
    description: 'Integrative health clinic combining conventional medicine with holistic wellness approaches. Our team of physicians, nutritionists, and therapists work together for whole-person care.',
    tags: ['Primary Care', 'Wellness', 'Holistic'],
    featured: false,
    verified: true,
    priceRange: '$$',
    color: '#56A356',
    initials: 'WF',
  },
  {
    id: '5',
    name: 'Swift Fix Plumbing',
    category: 'services',
    rating: 4.5,
    reviewCount: 276,
    address: '555 Service Road',
    city: 'Chicago, IL',
    phone: '+1 (773) 555-0505',
    website: 'https://example.com',
    hours: 'Mon–Sat 7am–8pm · Emergency 24/7',
    description: 'Licensed and fully insured plumbers serving residential and commercial clients since 1998. We handle everything from leaky faucets to full pipe replacements.',
    tags: ['Plumbing', 'Emergency', 'Licensed'],
    featured: false,
    verified: true,
    priceRange: '$$',
    color: '#5B8FC4',
    initials: 'SF',
  },
  {
    id: '6',
    name: 'Prestige Auto Detailing',
    category: 'services',
    rating: 4.8,
    reviewCount: 143,
    address: '321 Shine Lane',
    city: 'Los Angeles, CA',
    phone: '+1 (310) 555-0606',
    website: 'https://example.com',
    hours: 'Mon–Sun 8am–6pm',
    description: 'Premium auto detailing service restoring your vehicle to showroom condition. We use only professional-grade products and techniques for lasting results.',
    tags: ['Auto Detail', 'Ceramic Coat', 'Interior'],
    featured: true,
    verified: true,
    priceRange: '$$$',
    color: '#C47C4A',
    initials: 'PA',
  },
  {
    id: '7',
    name: 'The Vintage Vault',
    category: 'shopping',
    rating: 4.6,
    reviewCount: 98,
    address: '67 Antique Row',
    city: 'Portland, OR',
    phone: '+1 (503) 555-0707',
    website: 'https://example.com',
    hours: 'Tue–Sun 10am–6pm',
    description: 'Curated collection of vintage clothing, furniture, and collectibles from every decade. Each piece is carefully selected and authenticated by our expert team.',
    tags: ['Vintage', 'Antiques', 'Collectibles'],
    featured: false,
    verified: false,
    priceRange: '$$',
    color: '#A07850',
    initials: 'VV',
  },
  {
    id: '8',
    name: 'Fresh Market Co.',
    category: 'shopping',
    rating: 4.7,
    reviewCount: 421,
    address: '890 Farmers Way',
    city: 'Denver, CO',
    phone: '+1 (720) 555-0808',
    website: 'https://example.com',
    hours: 'Daily 7am–9pm',
    description: 'Your neighborhood grocer for organic produce, artisanal foods, and specialty items. We partner with local farmers and producers to bring you the best.',
    tags: ['Organic', 'Local', 'Specialty'],
    featured: false,
    verified: true,
    priceRange: '$$',
    color: '#5A9E5A',
    initials: 'FM',
  },
  {
    id: '9',
    name: 'Starlight Cinema',
    category: 'entertainment',
    rating: 4.4,
    reviewCount: 634,
    address: '12 Theater Plaza',
    city: 'Nashville, TN',
    phone: '+1 (615) 555-0909',
    website: 'https://example.com',
    hours: 'Daily 11am–11pm',
    description: 'Premium cinematic experiences with IMAX, Dolby Atmos, and luxury recliner seating. Enjoy gourmet concessions and curated film selections every week.',
    tags: ['Movies', 'IMAX', 'Luxury Seating'],
    featured: true,
    verified: true,
    priceRange: '$$',
    color: '#6B5B9E',
    initials: 'SC',
  },
  {
    id: '10',
    name: 'CodeCraft Academy',
    category: 'education',
    rating: 4.9,
    reviewCount: 287,
    address: '400 Tech Boulevard',
    city: 'San Francisco, CA',
    phone: '+1 (415) 555-1010',
    website: 'https://example.com',
    hours: 'Mon–Fri 9am–8pm · Sat 10am–4pm',
    description: 'Immersive coding bootcamps and weekend workshops for all skill levels. From web development to machine learning, we help students launch tech careers.',
    tags: ['Coding', 'Bootcamp', 'Tech'],
    featured: false,
    verified: true,
    priceRange: '$$$',
    color: '#3E7DC4',
    initials: 'CC',
  },
  {
    id: '11',
    name: 'Harbor View Realty',
    category: 'real-estate',
    rating: 4.8,
    reviewCount: 156,
    address: '55 Waterfront Drive',
    city: 'Boston, MA',
    phone: '+1 (617) 555-1111',
    website: 'https://example.com',
    hours: 'Mon–Sat 9am–6pm',
    description: 'Award-winning real estate agency specializing in luxury waterfront properties and investment opportunities. Our experienced agents guide you through every step of the process.',
    tags: ['Luxury', 'Waterfront', 'Investment'],
    featured: true,
    verified: true,
    priceRange: '$$$$',
    color: '#3A6E8C',
    initials: 'HV',
  },
  {
    id: '12',
    name: 'Green Leaf Yoga',
    category: 'healthcare',
    rating: 4.8,
    reviewCount: 203,
    address: '34 Serenity Lane',
    city: 'Boulder, CO',
    phone: '+1 (303) 555-1212',
    website: 'https://example.com',
    hours: 'Mon–Sun 6am–9pm',
    description: 'A welcoming yoga studio offering classes for all levels. From gentle restorative flows to dynamic Ashtanga, find your practice with our certified instructors.',
    tags: ['Yoga', 'Meditation', 'Wellness'],
    featured: false,
    verified: true,
    priceRange: '$',
    color: '#4A8C4A',
    initials: 'GL',
  },
];
